#!/bin/bash

drupal_user=${2:-application}
httpd_group="${3:-www-data}"

cd /var/www/html/web
printf "Changing ownership of all contents of :\n user =>  \t group => ""\n"
chown -R ${drupal_user}:${httpd_group} .

printf "Changing permissions of all directories of drupal\n"
find . -type d -exec chmod u=rwx,g=rx,o= '{}' \;

printf "Changing permissions of all files of drupal"
find . -type f -exec chmod u=rw,g=r,o= '{}' \;

printf "Changing permissions of /sites \n"
cd sites
find . -type d -name files -exec chmod ug=rwx,o= '{}' \;

printf "Changing permissions of all files inside"
printf "Changing permissions of all directories inside all.\n"
for x in ./*/files; do
  find ${x} -type d -exec chmod ug=rwx,o= '{}' \;
  find ${x} -type f -exec chmod ug=rw,o= '{}' \;
done
echo "Done setting proper permissions on files and directories"

echo "Mounting EFS"
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-56c7939f.efs.eu-west-1.amazonaws.com:/ /var/www/html/web/sites/default/files

cd /var/www/html
echo "Start compose install"
composer install
echo "Start cd web"
cd web
echo "Start drush cr"
drush cr
echo "Start drush cim -y"
drush cim -y
echo "Start drush updb -y"
drush updb -y
echo "Start drush cr"
drush cr
echo "End entrypoint"
